### ISSUE TITLE
Showing me black screen

### ISSUE THREAD

**Issue by kishanverma26** [akshay2211/PixImagePicker#31] opened 2018-07-30 07:44 UTC
Showing me black screen instead of camera preview

**Comment by akshay2211** [comment] 2018-07-30 08:38
Hello @kishanverma26,
Is this issue reproducible or device specific. 
can you provide more detail on this scenario.
like what device are you using or any snippet of your code where you are using this.

**Comment by kishanverma26** [comment] 2018-07-31 07:10
@akshay2211  it was not showing in other devices as well it was giving me some verbose logs like this 

**TextureView not displayed due to low memory**

**Comment by kelvohh** [comment] 2018-07-31 13:57
iam getting the same issue

**Comment by kishanverma26** [comment] 2018-08-01 12:40
@kelvohh  still same issue

TextureView not displayed because it is too large to fit into a software layer (or drawing cache), needs 14520000 bytes, only 9849600 available

**Comment by hb-coe** [comment] 2018-09-07 09:29
In my Samsung S8 also have same issue to show black screen only in front and back camera.
My Device android OS version is 8.0
Logcat error is:
W/View: TextureView not displayed because it is too large to fit into a software layer (or drawing cache), needs 14785200 bytes, only 9590400 available

**Comment by akshay2211** [comment] 2020-05-12 14:44
this has been resolved in the latest version on [pix](https://github.com/akshay2211/PixImagePicker)

**Closed by akshay2211** 2020-05-12 14:44 UTC
Labels: bug
