### ISSUE TITLE
Camera Preview is distorted on Samsung mobile

### ISSUE THREAD

**Issue by rodrigommacedo** [akshay2211/PixImagePicker#12] opened 2018-06-14 13:35 UTC
Camera Preview is distorted on Samsung mobile (SM-G531H - Android 5.1.1 - Mode Portrait)

**Comment by akshay2211** [comment] 2018-06-15 05:58
Hello @rodrigommacedo,
Can you provide any screenshots or a bit more detailed info?
Have you tried it in another hardware?

**Comment by sabieber** [comment] 2018-06-15 07:38
I can reproduce the issue with the Pixel 2 XL API 26 emulator. Dont know if that helps finding the root of the issue.

Just the preview is affected, the resulting image seems fine.

![image](https://user-images.githubusercontent.com/2427877/41456127-cbaa42d6-707f-11e8-894c-1370d9fdb7cc.png)

**Comment by rodrigommacedo** [comment] 2018-06-15 12:39
I tested on mobile phone z2 worked

Print Samsung SM-G531H:
![0294c077-c139-4e6e-b9b0-2e4175104c28](https://user-images.githubusercontent.com/1245391/41468101-27bbacd2-707f-11e8-864d-7cd401b5189c.jpg)


Photo Original:
![unnamed](https://user-images.githubusercontent.com/1245391/41468296-e1c9b916-707f-11e8-9039-c360befd0b39.jpg)

**Comment by sabieber** [comment] 2018-06-19 13:55
@akshay2211 This seems to be an issue with the CameraKit library https://github.com/CameraKit/camerakit-android/issues/288

**Comment by holpmaster** [comment] 2018-06-22 05:49
I have also experienced the same on a Xioami Mi6.

According to the CameraKit guys 1.0.0 is supposed to fix this issue, but I updated and it didn't:
https://github.com/CameraKit/camerakit-android/pull/318

Is there anything else that could be done to fix it?

**Comment by praslnx8** [comment] 2018-06-27 14:07
Even I am getting these issue in Lenova K5 vibe.

**Comment by waelsyrian996** [comment] 2018-07-01 12:14
I am having the same issue HTC devices, but I did something (with risk) and helped me.
I added PixImagePicker as a module then, I changed the CameraKit version to 1.0.0 preview 

check this link:
https://github.com/CameraKit/camerakit-android/pull/318

and made the changes in the process of dealing with the camera and it works with me.

**Comment by sabieber** [comment] 2018-07-01 12:15
@waelsyrian996 Could you perhaps create a PR of these changes?

**Comment by akshay2211** [comment] 2018-07-01 17:48
I am working on switching to [Fotoapparat](https://github.com/RedApparat/Fotoapparat) from Camera kit, this will provide a stable camera view, I will try to update it by next 1 or 2 days.

**Comment by akshay2211** [comment] 2018-07-08 18:33
Sorry for the delay, wasn't able to do much in last few days,
The above-mentioned change is been done in new version 1.0.10.

**Comment by sabieber** [comment] 2018-07-09 12:41
Why is such a major change just a change in the bugfix part of the version-number? Thats not really how semantic versioning is supposed to work 😅 Should be at least 1.1 if not 2.0

**Comment by sabieber** [comment] 2018-07-09 12:54
Bug seems to be fixed on my end 👍

**Comment by akshay2211** [comment] 2018-07-10 04:24
@sabieber no issues ill convert it to 2.0 , Thank you for letting me know.

**Closed** 2018-07-14 18:32 UTC
