### ISSUE TITLE
java.lang.IndexOutOfBoundsException onBackPressed

### ISSUE THREAD

**Issue by intips** [akshay2211/PixImagePicker#59] opened 2019-01-09 10:43 UTC
> java.lang.IndexOutOfBoundsException: Index: 392, Size: 103
java.util.ArrayList.get (ArrayList.java:437)
com.fxn.pix.Pix.onBackPressed (SourceFile:796)
android.app.Activity.onKeyUp (Activity.java:3229)
android.view.KeyEvent.dispatch (KeyEvent.java:2792)
android.app.Activity.dispatchKeyEvent (Activity.java:3537)
androidx.core.app.ComponentActivity.superDispatchKeyEvent (SourceFile:108)
androidx.core.view.KeyEventDispatcher.dispatchKeyEvent (SourceFile:84)
androidx.core.app.ComponentActivity.dispatchKeyEvent (SourceFile:126)
androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent (SourceFile:535)
androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent (SourceFile:59)
androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent (SourceFile:2533)
com.android.internal.policy.DecorView.dispatchKeyEvent (DecorView.java:403)
android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:5661)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5529)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4987)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5040)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5006)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:5160)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:5014)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:5217)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4987)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5040)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5006)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:5014)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4987)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5040)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5006)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:5193)
android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent (ViewRootImpl.java:5354)
android.view.inputmethod.InputMethodManager$PendingEvent.run (InputMethodManager.java:2783)
android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback (InputMethodManager.java:2291)
android.view.inputmethod.InputMethodManager.finishedInputEvent (InputMethodManager.java:2282)
android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished (InputMethodManager.java:2758)
android.view.InputEventSender.dispatchInputEventFinished (InputEventSender.java:141)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:386)
android.os.Looper.loop (Looper.java:169)
android.app.ActivityThread.main (ActivityThread.java:7470)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:958)

**Comment by akshay2211** [comment] 2019-03-09 07:22
Hello @intips 
can you provide more details?

**Comment by Qism0** [comment] 2019-04-29 09:01
Hi,

I've got the same issue, I though it would be fixed in this commit https://github.com/akshay2211/PixImagePicker/commit/537022a28d6fa27deb097c3adb44004906105944 but I still face this bug. However,  I cannot reproduce it  myself, I got it from my community on crashlytics in fabric.io

Enclosed screenshot of the crash.

![Screen Shot 2019-04-29 at 10 40 27 AM](https://user-images.githubusercontent.com/9129812/56884835-40a34e80-6a6b-11e9-9085-bcd6ed00e3a6.png)

I guess we can solve it by adding a try/catch, synchronize the `selectionList` and `onBackPressed()` or making sure we do not call `onBackPressed()` more than one time. It might be another function that modifies the list after `if (selectionList.size() > 0) {` have been called...

Thank you for the great work you have been doing here :-D

**Comment by Qism0** [comment] 2019-05-06 09:41
Hi @intips,

I tried to fix the bug on this commit https://github.com/Qism0/PixImagePicker/commit/8a262fbb666109fe0b7b80faec57900fa958750e on my fork which is updated (last core release merged) and will be maintained in the future.

Let me know if you still face the issue.

Regards
-73k05-

**Closed** 2020-08-04 20:27 UTC
Labels: wontfix
