### ISSUE TITLE
it should not be ask for microphone permission if ExcludeVideos is set to false

### ISSUE THREAD

**Issue by shobhitgupta1245** [akshay2211/PixImagePicker#114] opened 2020-04-24 08:37 UTC

**Comment by shobhitgupta1245** [comment] 2020-04-24 08:38
I think you will need to set Audio.off on cameraview

**Comment by akshay2211** [comment] 2020-04-24 09:28
Thanks for the PR
the issue is resolved in the latest [release](https://github.com/akshay2211/PixImagePicker#download)

**Comment by shobhitgupta1245** [comment] 2020-04-24 09:28
@akshay2211  Are you planning to move to media store since getExternalDir() is deprecated now

**Comment by shobhitgupta1245** [comment] 2020-04-24 09:28
@akshay2211  Thanks :)

**Comment by ThinClient** [comment] 2020-04-24 09:41
You guys are awesome thanks for resolving the issue.

**Closed** 2020-04-24 10:10 UTC

**Comment by akshay2211** [comment] 2020-04-24 10:17
Make sure to star the library 😊
